### ISSUE TITLE
[Bug] Postcard does not handle serde attribute skip_serializing_if properly

### ISSUE THREAD

**Issue by tugtugtug** [jamesmunns/postcard#122]
```
#[test]
fn test_serialize_flow_context() {
	#[derive(PartialEq, Debug, Default, Deserialize, Serialize, Clone)]
	pub struct Test {
		/// The id of the policy the lookup matched on
		#[serde(default, rename = "pid", skip_serializing_if = "Option::is_none")]
		pub policy_id: Option<String>,
		/// The name of the policy the lookup matched on
		#[serde(default, rename = "pname", skip_serializing_if = "Option::is_none")]
		pub policy_name: Option<String>,
	}
	let binary = postcard::to_allocvec(&Test::default()).unwrap();
	let _: Test = postcard::from_bytes(binary.as_ref()).unwrap();
}
```
This fails, and if I remove the `skip_serializing_if` attributes from the fields, then it works.

**Comment by jamesmunns** [comment]
In general, postcard does not handle many of serde's attributes that only apply to self describing formats. See also #29.

Docs PRs welcome that make this more clear.

**Comment by elrafoon** [comment]
I just hit the same problem.

And it's much worse if the same type needs to be serializes/deserialized with postcard and some other serializer - json, cbor, ...

Then it may be not possible to just adjust serde attributes to the postcard's taste, because it would break formatting for other serializer (that i.e. must fullfil some json schema).

**Comment by jamesmunns** [comment]
@tugtugtug:

> But is there anything postcard can do to ensure the consistency of the behaviour between its own serialization and the deserialization

I am not aware of any way to statically "notice" that round-trips will fail if you use any of the relevant serde attributes, nor am I aware of any way of preventing it in the first place.

If you find a way, I am very interested!

**Comment by jamesmunns** [comment]
I've opened https://github.com/jamesmunns/postcard/issues/125 to track this, please feel free to discuss there if you have potential solutions or ideas.
