### ISSUE TITLE
This repository doesn't seem to have continuous integration

### ISSUE THREAD

**Issue by ia0** [jamesmunns/postcard#144]
This crate already has quite a few dependents but doesn't have any form of continuous integration as far as I can tell. This seems a bit risky and makes this crate looks less reliable. In particular, in #142 I realized that the `tests/schema.rs` could never have been run because of the wrong `cfg(feature = "")` gating the whole file. I understand this feature is experimental, but I would expect a repository to contain a few dead-code as possible, including tests.

Are there any plans of adding continuous integration?

**Comment by jamesmunns** [comment]
@ia0 thank you for all the support today!
