### ISSUE TITLE
Added Dependency on Arc

### ISSUE THREAD

**Issue by sjudson** [jamesmunns/postcard#167]
The 1.0.9 release of `postcard` appears to have added (through https://github.com/jamesmunns/postcard/commit/ae7f40b21533ef314d789ae18f5c45508d2a3c32) a dependency for the `alloc` feature on `alloc::sync::Arc`. 

Per the Rust docs (https://doc.rust-lang.org/alloc/sync/index.html), this is unsupported on certain targets:

> Note: This module is only available on platforms that support atomic loads and stores of pointers. This may be detected at compile time using #[cfg(target_has_atomic = "ptr")].

Would it be possible to gate the use of `Arc` against the `target_has_atomic` configuration check recommended by the docs?

I'd be happy to open a PR to do so if that would be helpful.

**Comment by jamesmunns** [comment]
@sjudson I would appreciate a PR, yes! Feel free to @ me when it is open.

**Comment by sjudson** [comment]
> @sjudson I would appreciate a PR, yes! Feel free to @ me when it is open.

Great, will do.

**Comment by jamesmunns** [comment]
Released as v1.0.10, thank you @sjudson!

https://github.com/jamesmunns/postcard/releases/tag/v1.0.10
