### ISSUE TITLE
impl `Schema` for `NamedType` et. al

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/postcard#172]
I attempted to implement `Schema` for the various types associated with schemas, like `SdmTy` and such.

However, this ends up causing an unbounded cycle: NamedType contains an SdmTy that can contain a NamedTy, etc. This can be seen in: https://github.com/jamesmunns/postcard/tree/james/schema-schema

I don't know if there is a way around this, at least with the currently recursive definition of how we do schemas.

For now, I think I'm just going to have a `NewType([u8])` if I want to send schemas, and do the deserialization as a second step if I want to send schemas over postcard-rpc.

**Comment by max-heller** [comment]
> do the deserialization as a second step if I want to send schemas over postcard-rpc.

Is there a plan to make schemas implement `Deserialize`? I've been wanting the ability to send schemas around and deserialize bytes into a generic representation (analogous to [`serde_json::Value`](https://docs.rs/serde_json/latest/serde_json/enum.Value.html)) based on a schema, but Schema only supporting `'static` references seems like a blocker

**Comment by jamesmunns** [comment]
Check out https://github.com/jamesmunns/postcard/tree/james/owned-schema

And https://github.com/jamesmunns/postcard-dyn/

I'm actively working on it now

**Comment by max-heller** [comment]
> Check out https://github.com/jamesmunns/postcard/tree/james/owned-schema
> 
> And https://github.com/jamesmunns/postcard-dyn/
> 
> I'm actively working on it now

Exciting, thanks for the pointers!

**Comment by jamesmunns** [comment]
And if you want a preview of what I'm working on it for: https://onevariable.com/poststation/

**Comment by jamesmunns** [comment]
Implemented in #170
