### ISSUE TITLE
Unused bytes with from_bytes 

### ISSUE THREAD

**Issue by l4l** [jamesmunns/postcard#18]
A [doc](https://docs.rs/postcard/0.4.3/postcard/fn.from_bytes.html) for `postcard::from_bytes` states:

> Deserialize a message of type T from a byte slice. The unused portion (if any) of the byte slice <b>is returned</b> for further usage

Although the function doesn't return unused sub-slice or some other hint about bytes that has been read. Is is documentation issue, or I'm missing something?

P.S. in `from_bytes_cobs` doc comment looks fine.

**Comment by jamesmunns** [comment]
So, the signature for this function is:

```
pub fn take_from_bytes<'a, T>(s: &'a [u8]) -> Result<(T, &'a [u8])> where
    T: Deserialize<'a>, 
```

It returns `Result<(T, &'a [u8])>`, where `T` is the deserialized type, and `&'a [u8]` is the remaining unused slice. The intended usage would be like:

```rust
let total buf: &[u8] = &[.........];

let (a, remainder_a) = postcard.take_from_bytes(buf).unwrap();
let (b, remainder_b) = postcard.take_from_bytes(remainder_a).unwrap();
let (c, remainder_c) = postcard.take_from_bytes(remainder_b).unwrap();
// ...
```

Does that make sense?

**Comment by jamesmunns** [comment]
Oh, sorry, I was looking at `take_from_bytes`, not `from_bytes`! c.f. https://docs.rs/postcard/0.5.0/postcard/fn.from_bytes.html.

Yes, this is a documentation bug. Would you like to open a PR to fix the docs? Thanks for reporting!

**Comment by l4l** [comment]
> Oh, sorry, I was looking at take_from_bytes, not from_bytes!

Yep, sorry, mess up with a wrong link.

> Would you like to open a PR to fix the docs?

Yeah, sure
