### ISSUE TITLE
postcard-schema: inconsistent schema names for `[T]` and `[T; N]`

### ISSUE THREAD

**Issue by max-heller** [jamesmunns/postcard#182]
Is there a reason for `[T]`'s schema name to be `&[T]` while `[T; N]`'s is `[T; N]` (no `&`)? It seems like it'd be more consistent to remove the `&`.

https://github.com/jamesmunns/postcard/blob/70111772ee231364daeac7cd11063352f19bc930/source/postcard-schema/src/impls/builtins_nostd.rs#L91-L102

**Comment by jamesmunns** [comment]
I think that's reasonable. The idea was to make it clear the former is a *slice* (e.g. with a len), whereas the latter is an *array*. I don't often use bare unsized slices, so I used `&[T]` out of habit.

That being said, `[T]` is probably more consistent.
