### ISSUE TITLE
#[serde(flatten)] causes serialization to fail

### ISSUE THREAD

**Issue by akhilles** [jamesmunns/postcard#29]
To reproduce:

```rust
use serde::{Serialize};

#[derive(Serialize)]
pub struct Outer {
    #[serde(flatten)]
    field2: Inner,
}
#[derive(Serialize)]
pub struct Inner {
    field1: Vec<u8>,
}
fn main() {
    let data = Outer {
        field2: Inner {
            field1: Vec::new(),
        }
    };
    postcard::to_allocvec(&data).unwrap();
}
```

fails with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerializeSeqLengthUnknown', src/main.rs:18:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by maxammann** [comment]
Also just stumbled upon this, not really blocking as I see flatten as a convenience feature but it would still be cool :)

**Comment by jamesmunns** [comment]
I think this is the same issue as #58, in that we can't really support flattened items.

I'll leave this open until I add more robust note of this in the docs for v1.0.0

**Comment by tgnottingham** [comment]
To anyone else stumbling on this, this is more of a serde issue than a postcard one.

See the original issue https://github.com/serde-rs/serde/issues/119 for discussion on the feature only being supported for self-describing formats. Based on more recent issues, it doesn't sound like we'll be seeing support for non-self-describing formats any time soon, unless someone comes up with a way of doing it that has better tradeoffs than the existing ideas on how to do it.

**Comment by jamesmunns** [comment]
Agreed. Docs PRs welcome that note this limitation.
