### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Diggsey** [jamesmunns/postcard#40]
Just saw that 0.7 had been released - would be great if there was a changelog to aid in upgrading :)

**Comment by jamesmunns** [comment]
That's a great idea! I'll try and start including this for future releases, and try to summarize the 0.6.x -> 0.7.x changes as well.

IIRC, 0.7 was just to bump the dependency on `heapless`, and to support const-generics (and remove the dependency on typenum).

**Comment by jamesmunns** [comment]
Started doing this in v0.7.1! Thanks again for the suggestion :)
