### ISSUE TITLE
Word aligned slices?

### ISSUE THREAD

**Issue by huntc** [jamesmunns/postcard#44]
I have a use case where I’m writing the serialised slice to nvmc, which requires the slice to be word aligned. I’m wondering if it’d be useful then to have a variant of to_slice that provides a word aligned slice. Thoughts? Thanks.

**Comment by jamesmunns** [comment]
Hey @huntc, you mean the destination needs to be word aligned?

IMO, this is more of a property of the caller, e.g. you should make sure your destination slice is word aligned before calling `to_slice`, either using a wrapper type, like:

```rust
#[repr(align(4))]
struct DestinationBuf<const N: usize> {
    bytes: [u8; N]
}
```

or some wrapper method that "skips" the first unaligned bytes.

Is there some design you had in mind for how postcard could handle this instead?

**Comment by huntc** [comment]
Sorry for the slow reply. And thanks for the answer.
