### ISSUE TITLE
pre-compute size of serialized data

### ISSUE THREAD

**Issue by x37v** [jamesmunns/postcard#46]
I'm using the slice flavor, I'm wondering if it is possible to compute the size of the serialized data without actually serializing?

**Comment by gauteh** [comment]
Hi,

I am trying out postcard as a format for storing data on a SD-card. There will be a large number of data-packages so they will exhaust the number of files allowed on FAT32. embedded-sdmmc does not (yet) support creating directories, so I can't solve it by putting the files in dirs. So now I am considering putting many packages in each file. I will use COBS between the packages, but I need to know the serialized size of the packages. The data-package is a fixed size (no variable length fields): https://github.com/gauteh/sfy/blob/main/sfy-buoy/src/axl.rs#L10 .

- Can I compute the size of a serialized package?
- If I determine it experimentally, is it stable? Will it be the the exact same size regardless of the struct contents?

Regards, Gaute

**Comment by ryankurte** [comment]
heya, i have a very similar problem and i'm not sure the macros cover the ability to pre-compute size when serializing? (or, i have missed how this can be used to achieve this).

i'm looking for something like `postcard::encoded_len<T: Serialize>(t: &T) -> usize` / equivalent to `prost`'s [`Message::encoded_len()`](https://docs.rs/prost/latest/prost/trait.Message.html#tymethod.encoded_len), that's basically a no-op encode outputting the buffer size required.

**Comment by dignifiedquire** [comment]
@jamesmunns 
Any updates here? I am running into an issue with this, for preallocating buffers when serializing. The reason `MAX_SIZE` doesn't work is because I have `&[u8]` and `String` in my data. Maybe there could be a way to calculate the size based on `MAX_SIZE` + `.len()` dynamically?

**Comment by jamesmunns** [comment]
Oops, forgot my "more below" part:

We COULD extend the MAX derive to take attributes on certain items, like:

```rust
#[derive(Serialize, Deserialize, MaxSize)]
struct Demo<'a> {
    arr: [Foo; 5],
    #[postcard(max_hint = 128)]
    sli: &[Bar],
    #[postcard(max_hint = 64)]
    hst: String
}
```

This covers the `!Sized` case I described above as 1b.

**Comment by dignifiedquire** [comment]
@jamesmunns just created #86 which should fix things up
