### ISSUE TITLE
to_slice functions. Documentation does not match the code.

### ISSUE THREAD

**Issue by alex-gh** [jamesmunns/postcard#49]
I have noticed that the Documentation for the to_slice functions does not match the code.
https://docs.rs/postcard/0.7.2/postcard/fn.to_slice.html and https://docs.rs/postcard/0.7.2/postcard/fn.to_slice_cobs.html say that the function returns two slices, yet only one slice is returned in the code.

**Comment by jamesmunns** [comment]
Thanks for reporting! This has been fixed in main, and will be part of the 1.0.0 release.
