### ISSUE TITLE
`take_from_bytes_cobs` not consuming trailing null bytes inserted by `to_slice_cobs`

### ISSUE THREAD

**Issue by DusterTheFirst** [jamesmunns/postcard#50]
`take_from_bytes_cobs` returns two things on success. The de-serialized structure and any leftover buffer. When de-serializing using `take_from_bytes_cobs` it would make sense for the trailing null byte to be consumed by the de-serialization since it is somewhat part of the data. It also is unintuitive that the user will end up with a buffer with a single null byte after de-serializing cobs data.

My specific use case is as follows:
Calling `postcard::to_slice_cobs` on my data returns `[2, 1, 0]` and calling `postcard::take_from_bytes_cobs` returns `(<my data>, &[0])`

**Comment by jamesmunns** [comment]
Hey @DusterTheFirst, thanks for reporting this! I managed to track down the issue. `take_from_bytes_cobs` was returning the number of DECODED bytes, not the number of SOURCE BYTES used during decoding.

This was... very wrong, and not a useful number.

Thanks again!
