### ISSUE TITLE
can you influence numeric representation of enum variants?

### ISSUE THREAD

**Issue by rpcesar** [jamesmunns/postcard#55]
Hi, I am trying to use postcard as a means of representing an enum variant of "message types". I am of the understanding that this system tags each variant using it a varint, which is great, however I would really like to be able to control the layout of these assigned numbers in some way. IE specifying numeric offsets to some of them making it sparse. The use case for this is allowing feature-gated variants without messing up the integrity of the format as a whole. I realize this could probably be accomplished with macros and fake entities, but that would still lead to convoluted switch statements and bad compile times. Any novel way I cam accomplish this within the system?

Thanks!

**Comment by jamesmunns** [comment]
Hi @rpcesar, I don't believe so, unfortunately. If you find one, I'd be happy to capture it as an example/docs!

In previous projects, I've used a small (non-proc) macro to switch between a real/fake impl. Hopefully regular macros should have less of a code impact.

**Comment by jamesmunns** [comment]
Since I don't think postcard can handle this, I'm going to close the issue. If you find a (potential) way to handle this, please feel free to reopen or create a new issue/PR!
