### ISSUE TITLE
Q: How to decode the postcard encoded binary in std enviroment?

### ISSUE THREAD

**Issue by yaoxin1995** [jamesmunns/postcard#85]
Hey,

I have two applications that communicate via a pipe. The first one runs on std env and the second one on the no std env.

So for example, the second app encodes the data using postcard and sends it to the first app.

How can the first app decode the binary?

**Comment by jamesmunns** [comment]
Hey @yaoxin1995, there's two things going on here:

* Buffering incoming bytes from the stream, and finding a "frame". You might try using the `COBS` flavor, and the `CobsAccumulator` struct, which allow you to turn a stream of bytes into a stream of messages.
* Using `std` only helpers, like `to_stdvec()`, which require the `use-std` feature.

In general - anything that works in `no-std`, like `from_bytes()` will also work on `std`.

Does that help? Or are you still struggling with something?

**Comment by jamesmunns** [comment]
I'm going to close this, feel free to reopen it if you need.

**Comment by yaoxin1995** [comment]
Many thanks,it solved my problem
