### ISSUE TITLE
How to explicitly specify field order ?

### ISSUE THREAD

**Issue by luqasz** [jamesmunns/postcard#94]
Hi.

I am new to serde and postcard. I haven't seen any way of stating in which order should fields be serialized. Is it possible ?

**Comment by jamesmunns** [comment]
Hi @luqasz, this is talked about a bit in [the postcard spec](https://postcard.jamesmunns.com/wire-format.html#28---struct), but generally: fields get serialized in the order they are defined in Rust, including nested fields.

For example:

```rust
struct One {
    a: u32,
    b: u8,
    c: Two,
    f: bool,
}

struct Two {
    d: i8,
    e: i16,
}
```

Would look like this on the wire:

```
[ a ][ b ][ d ][ e ][ f ]
  |    |    |    |    \-> One::f
  |    |    |    \-> One::c::e
  |    |    \-> One::c::d
  |    \-> One::b
  \-> One::a
```

There isn't a way to reorder these, other than changing the definition of the struct you are serializing.

**Comment by luqasz** [comment]
ok. Thx. I will write same in c++ as I am writing embedded code in c++ and app in rust.
